name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.3=py38h261ae71_2
  - chardet=3.0.4=py38h06a4308_1003
  - conda=4.9.2=py38h06a4308_0
  - conda-build=3.21.4=py38h06a4308_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - cryptography=3.2.1=py38h3c74f83_1
  - cudatoolkit=11.0.221=h6bb024c_0
  - decorator=4.4.2=py_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - freetype=2.10.4=h5ab3b9f_0
  - glob2=0.7=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - intel-openmp=2020.2=254
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py38h06a4308_1
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libarchive=3.4.2=h62408e4_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - liblief=0.10.1=he6710b0_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py38hff7bd54_0
  - olefile=0.46=py_0
  - openssl=1.1.1i=h27cfd23_0
  - parso=0.7.0=py_0
  - patchelf=0.12=h2531618_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py38he98fc37_0
  - pkginfo=1.7.0=py38h06a4308_0
  - psutil=5.7.2=py38h7b6447c_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-lief=0.10.1=py38h403a769_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-libarchive-c=2.9=pyhd3eb1b0_0
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pytz=2020.5=pyhd3eb1b0_0
  - readline=8.0=h7b6447c_0
  - ripgrep=12.1.1=0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - setuptools=50.3.1=py38h06a4308_1
  - six=1.15.0=py38h06a4308_0
  - soupsieve=2.1=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.2=py38_cu110
  - tqdm=4.51.0=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - aiofiles==22.1.0
    - aiosqlite==0.18.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - babel==2.12.1
    - bleach==6.0.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - comm==0.1.3
    - debugpy==1.6.7
    - defusedxml==0.7.1
    - dnspython==2.1.0
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fqdn==1.5.1
    - huggingface-hub==0.13.3
    - importlib-metadata==6.1.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.1.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-fileid==0.8.0
    - jupyter-server-terminals==0.4.4
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.3
    - jupyterlab==3.6.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.22.0
    - markupsafe==2.1.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - nbclassic==0.5.5
    - nbclient==0.7.3
    - nbconvert==7.3.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - nltk==3.8.1
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.20.3
    - packaging==23.0
    - pandas==2.0.0
    - pandocfilters==1.5.0
    - pip==23.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - pure-eval==0.2.2
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-etcd==0.4.5
    - python-json-logger==2.0.7
    - pyyaml==6.0
    - pyzmq==25.0.2
    - regex==2023.3.23
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - send2trash==1.8.0
    - sniffio==1.3.0
    - stack-data==0.6.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torchelastic==0.2.1
    - tornado==6.2
    - traitlets==5.9.0
    - transformers==4.27.4
    - tzdata==2023.3
    - uri-template==1.2.0
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - y-py==0.5.9
    - ypy-websocket==0.8.2
    - zipp==3.15.0
prefix: /opt/conda
